// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImZRCxX_6OaBjVRfkU_0bhOe7bC9Lr-E',
    appId: '1:1078139584107:web:fbf3bde19f3b618bfc7b2e',
    messagingSenderId: '1078139584107',
    projectId: 'lifttry2',
    authDomain: 'lifttry2.firebaseapp.com',
    storageBucket: 'lifttry2.firebasestorage.app',
    measurementId: 'G-XSVDXW9W5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAyztrz8QGRn0KiXGwABZMIdV7i50Ss8E',
    appId: '1:1078139584107:android:52cd728a732361bafc7b2e',
    messagingSenderId: '1078139584107',
    projectId: 'lifttry2',
    storageBucket: 'lifttry2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpsxrdJf-HoD6HDVYlMRx1Zof6BAU6k8',
    appId: '1:1078139584107:ios:7208fda5a1103b19fc7b2e',
    messagingSenderId: '1078139584107',
    projectId: 'lifttry2',
    storageBucket: 'lifttry2.firebasestorage.app',
    iosBundleId: 'com.example.liftapp2',
  );
}
